import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Provider } from 'react-redux'
import { ChakraProvider, Grid } from '@chakra-ui/react'
import { ThemeProvider } from 'styled-components'
import theme, { colors } from 'styles/theme'

import Header from 'components/Header'
import Footer from 'components/Footer'
import store from 'state/store'

const MyApp = ({ Component, pageProps }: AppProps) => (
  <Provider store={store}>
    <ThemeProvider theme={{ colors }}>
      <ChakraProvider theme={theme}>
        <Grid minHeight="100vh" gridTemplateRows="auto 1fr auto">
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Header />
          <Component {...pageProps} />
          <Footer />
        </Grid>
      </ChakraProvider>
    </ThemeProvider>
  </Provider>
)

export default MyApp
