import Head from 'next/head'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'
import { ChakraProvider, Grid } from '@chakra-ui/react'
import { ThemeProvider } from 'styled-components'

import type { AppProps } from 'next/app'
import theme, { colors } from 'styles/theme'
import { mediaQueries } from 'styles/breakpoints'

import { persistor, wrapper } from 'state/store'

import { Header } from 'components/Header'
import Footer from 'components/Footer'
import AuthGuard from 'components/Auth/Guard'

const MyApp = ({ Component, ...rest }: AppProps) => {
  const { store, props } = wrapper.useWrappedStore(rest)

  return (
    <Provider store={store}>
      <ThemeProvider theme={{ colors, mediaQueries }}>
        <ChakraProvider theme={theme}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Grid minHeight="100vh" gridTemplateRows="auto 1fr auto">
            <Header />
            <PersistGate loading={null} persistor={persistor}>
              <AuthGuard>
                <Component {...props.pageProps} />
              </AuthGuard>
            </PersistGate>
            <Footer />
          </Grid>
        </ChakraProvider>
      </ThemeProvider>
    </Provider>
  )
}

export default MyApp
