import type { NextPage } from 'next'
import Head from 'next/head'
import { Grid, Text } from '@chakra-ui/react'
import Header from 'components/Header'
import Footer from 'components/Footer'

const Home: NextPage = () => (
  <Grid minHeight="100vh" gridTemplateRows="auto 1fr auto">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
    <main>
      <Text
        bgGradient="linear(to-l, #7928CA, #FF0080)"
        bgClip="text"
        fontSize="6xl"
        fontWeight="extrabold">
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </Text>
    </main>
    <Footer />
  </Grid>
)

export default Home
